### ISSUE TITLE
Lack of Windows support 

### ISSUE THREAD

**Issue by joneldiablo** [andi1984/vscode-tinypng#1]
error showed:
ENOENT: no such file or directory, open 'C:\c:\Users\User\multiplica\infonavit-projects\infonavit-private\src_images\demo\AcroRd32_2018-01-02_15-01-24.png'

the disk letter is repeat, I think VS put the X:\ preffix so is necesary cut from the beginin of tthe path the "x:\"

**Comment by andi1984** [comment]
@joneldiablo Thanks for informing me about this. I'm sorry about it and try to fix it asap!

**Comment by andi1984** [comment]
@joneldiablo One more question: Did you use TinyPNG extension on this one single file mentioned in the path or on a parent folder?

**Comment by andi1984** [comment]
@joneldiablo I released a new version 0.2.0 which is fixing the Windows issue. Thanks for reporting and sorry for the inconveniences!

**Comment by joneldiablo** [comment]
Wow thanks! =D
