### ISSUE TITLE
API - code

### ISSUE THREAD

**Issue by gxg10** [andi1984/vscode-tinypng#3]
This may sound stupid, but how do i provide the API code to activate the extension? Kind regards

**Comment by andi1984** [comment]
@gxg10 Hi. There is a setting in VSCode coming with this extension called `tinypng.apiKey`. There you should be able to enter your API key.

**Comment by andi1984** [comment]
@gxg10 Does this solve your issue? I will nevertheless add some screenshots to the documentation as it seems to be not super obvious.
