### ISSUE TITLE
expect many apikeys

### ISSUE THREAD

**Issue by jackPanyj** [andi1984/vscode-tinypng#4]
now the apiKeys' type is the string.

expect that is any string[].

when it reaches the amount of 500, it can auto use the next key.

**Comment by andi1984** [comment]
@jackPanyj Thank you for your idea of managing many API keys, but I'm against supporting this functionality for two reasons:

1. It would bypass the TinyPNGs monetization system (cf. [their pricing rules](https://tinypng.com/developers))
2. If you need to manage multiple kinds of _profiles_, you can already do that overriding or defining the API keys on a workspace level in VSCode settings (e.g. API keys for a personal side-project and a corporate project).

So I decided not to implement that idea.
