### ISSUE TITLE
[Future Request] Option for not overwriting file

### ISSUE THREAD

**Issue by kanlukasz** [andi1984/vscode-tinypng#6]
Hello,

Great plugin. I have one useful idea.
The plugin currently compresses the file and replaces it. Overwriting is fine, but not always

I have two ideas (i'm not sure which one is better):

First idea:
- [x] Do not overwrite _(create second file named `<filename>_tifnified`)_

Second idea:
- [ ] Create backup _(backup before use and add `<filename>_backup` to the file name)_

**Comment by andi1984** [comment]
@kanlukasz Thanks. I would probably go with the idea that the extension should not touch the existing file, but rather create a new file and then it is the user's responsibility to replace the files. So I would go with your first idea.

**Comment by andi1984** [comment]
@kanlukasz The feature will be in newest extension version 0.3.0. Thanks again for your input on this!
