### ISSUE TITLE
No usage option for files if folder is not open

### ISSUE THREAD

**Issue by kanlukasz** [andi1984/vscode-tinypng#7]
If i just open some files in VsCode but i don't open folder, unfortunately there is no compress option
![obraz](https://user-images.githubusercontent.com/30685349/75245186-81740d00-57cd-11ea-9709-5f85b12d3b1c.png)

If i open this files with folder it works ok:
![obraz](https://user-images.githubusercontent.com/30685349/75245271-b2ecd880-57cd-11ea-8e32-4ee9070f37d1.png)

**Comment by andi1984** [comment]
@kanlukasz Thank you for reporting this. It is clearly not the way it is meant to be. I will try to replicate and fix the issue. Eventually I might come back to you with questions.

**Comment by andi1984** [comment]
@kanlukasz This seems, unfortunately, currently not supported by VSCode, cf. https://github.com/microsoft/vscode/issues/48981, so there is nothing I can do here, besides adding a sentence about this in the Readme. But you have to move the files to your workspace to have the actions available for now.
